# spring.datasource.url=jdbc:mysql://localhost:3306/destination?useSSL=false &
# allowPublicKeyRetrieval=true &
# serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=test@123
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# server.port=8082

# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=destination56662025@gmail.com
# spring.mail.password=jgpy ifsb zkzs ybki
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# spring.devtools.restart.enabled=true
# spring.devtools.livereload.enabled=true



# postgreSQL configuration
spring.datasource.url= jdbc:postgresql://neondb_owner:npg_Dya8HxkEK3GY@ep-old-heart-apb20r4w.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username= neondb_owner
spring.datasource.password= npg_Dya8HxkEK3GY
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8082

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_GMAIL@gmail.com
spring.mail.password=YOUR_NEW_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
